name: ADK Pull Request Triaging Agent

on:
  pull_request_target:
    types: [opened, reopened, edited]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'The Pull Request number to triage'
        required: true
        type: 'string'

jobs:
  agent-triage-pull-request:
    if: github.event_name == 'workflow_dispatch' || !contains(github.event.pull_request.labels.*.name, 'google-contributor')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests google-adk

      - name: Run Triaging Script
        env:
          GITHUB_TOKEN: ${{ secrets.ADK_TRIAGE_AGENT }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_GENAI_USE_VERTEXAI: 0
          OWNER: 'google'
          REPO: 'adk-python'
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number || github.event.inputs.pr_number }}
          INTERACTIVE: ${{ vars.PR_TRIAGE_INTERACTIVE }}
          PYTHONPATH: contributing/samples
        run: echo 'debug' && python -m adk_pr_triaging_agent.main
